version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mpcs_postgres
    environment:
      POSTGRES_USER: mpcs_user
      POSTGRES_PASSWORD: mpcs_password
      POSTGRES_DB: mpcs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: